
services:

  postgres:
    image: postgres:16

    container_name: alphamind-db

    restart: always

    environment:
      POSTGRES_USER: alphamind
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: alphamind

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: